### ISSUE TITLE
Spaces before declaring code block cause error

### ISSUE THREAD

**Issue by TedisAgolli** [Jsimmons--dev/freshDoc#8]
## Replicate: 

```md

[space][space]``` javascript @freshdoc ../../index.js:62-62
[space][space]```

```

## Command
```
freshdoc changes
```

## Error

(node:77539) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at getItems (file:///Users/tedisagolli/src/outlook-add-in/node_modules/freshdoc/lib/freshdoc-lib.mjs:34:77)
    at async getAllChanges (file:///Users/tedisagolli/src/outlook-add-in/node_modules/freshdoc/getBlockChanges.mjs:20:28)

## Fix
The spaces before the three ticks are causing the split to find extra stuff. We should trim before splitting

**Comment by TedisAgolli** [comment]
Closed in 3777576
